name: Build and Deploy Java App

on:
  push:
    branches:
      - main


jobs:
  build-and-push:
    env:
      APP_NAME: "IWA-JAVA"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ APP_NAME }}:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ APP_NAME }}:latest

  deploy-to-vm:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 172.188.112.254
          username: devops
          password: ${{ secrets.VM_SSH_PASSWORD }}
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ github.repository_owner }}/${{ APP_NAME }}:latest
            docker stop ${{ APP_NAME }} || true
            docker rm ${{ APP_NAME }} || true
            docker run -d --name ${{ APP_NAME }} -p 8080:8080 ghcr.io/${{ github.repository_owner }}/${{ APP_NAME }}:latest
